/** بيانات الموظفين — backend for the existing Employees sheet. */
const SPREADSHEET_ID='1merEUtN-JlAFsxjffXpoqvS3SIlwaP65E27n_1fyI7Y';
const SHEET_NAME='Employees';
const FIELDS=[
 ['code','كود'],['name','الاســـــــــــم '],['originalCompany',' الشركة '],['currentCompany','الشركة الحالية'],['currentSector',' القطاع  '],['currentGeneralDepartment','الاداره العامه'],['currentSubDepartment',' الاداره الفرعيه'],['jobTitle','مسمى الوظيفة '],['actualJob','الوظيفة فعلى '],['statisticsJob','مسمى الوظيفة للاحصائيات'],['uniform','الزى'],['gender','النـــــــــــــوع'],['birthDate','تاريخ الميلاد'],['retirementDate','تاريخ المعاش'],['appointmentDate','تاريح التعيين'],['age','السن الان '],['ageGroup','الفئة العمرية '],['ageAtAppointment','السن عند التعيين '],['totalService','مدة الخدمة الكلية '],['serviceType','نوع الخدمه'],['workType','نوع العمل'],['currentGrade','الدرجة الحالية'],['gradeDate','تاريخ الدرجة '],['appointmentJob','الوظيفة عند التعيين '],['jobDate','تاريخ الوظيفة '],['studySpecialization','التخصص الدراسى'],['qualificationDate','تاريخ المؤهل '],['currentQualificationTitle','مسمى المؤهل الحالى '],['currentQualificationType','نوع المؤهل الحالى '],['appointmentQualificationTitle2','مسمى مؤهل التعيين'],['appointmentQualificationType2','نوع مؤهل التعيين'],['appointmentQualificationTitle','مسمى المؤهل عند التعيين'],['appointmentQualificationType','نوع المؤهل عند التعيين '],['disabilityType','نوع الاعاقة'],['newJobGroups','المجموعات النوعية  '],['secondedJob','الوظيفة المنتدب عليها ( ان وجد )'],['secondedJob2','الوظيفة المنتدب عليها ( ان وجد )2'],['secondedCompany','شركة منتدب عليها'],['secondedSector','قطاع المنتدب عليه'],['secondedGeneralDepartment','ادارة عامة منتدب عليها'],['secondedDepartment','الادارة المنتدب عليها'],['secondmentStart','تاريخ الانتداب '],['secondmentEnd','تاريخ نهاية الانتداب '],['secondedJobGroup','المجموعة النوعية الجديدة المنتدب عليها'],['unpaidLeaveType','نوع الاجازة بدون مرتب  ( ان وجد ) '],['leaveMandatory','وجوبية الاجازة '],['leaveStart','تاريخ البداية'],['leaveEnd','تاريخ النهاية '],['militaryStatus','نوع المعاملة العسكرية '],['exemptionReason','سبب الاعفاء ( نهائي - مؤقت )'],['contractStart','تاريخ بداية التعاقد'],['contractEnd','تاريخ نهاية التعاقد'],['appointmentType','نوع التعيين'],['status','status'],['address','العنوان'],['phone','التليفون'],['governorate','المحافظة'],['addressExtra','الموقع'],['originalCompanyName','مسمى الشركة الاساسية'],['originalGeneralDepartment','الاداره العامة الأساسية'],['originalSubDepartment','مسمى الادارة الفرعية الاساسية'],['workSchedule','توقيت العمل']
];
const HEADER_KEYS=FIELDS.map(x=>x[1]);
// Preferred access control: set EMPLOYEE_DATA_ALLOWED_EMAILS to a
// comma-separated allowlist and deploy as "User accessing the web app" to
// your organization. Apps Script must be able to identify the signed-in user.
// EMPLOYEE_DATA_TOKEN is only a compatibility fallback for private testing;
// a token embedded in a browser page is not strong protection for HR data.
const TOKEN_PROPERTY='EMPLOYEE_DATA_TOKEN';
const ALLOWED_EMAILS_PROPERTY='EMPLOYEE_DATA_ALLOWED_EMAILS';
const COMPUTED=new Set(['age','ageGroup','ageAtAppointment','totalService']);

function setupEmployeesData(){const sh=getSheet();ensureSheetShape(sh);sh.setFrozenRows(1);sh.getRange(1,1,1,HEADER_KEYS.length).setFontWeight('bold').setBackground('#09243f').setFontColor('#ffffff').setWrap(true);return {ok:true,sheet:SHEET_NAME,rows:Math.max(0,sh.getLastRow()-1),columns:HEADER_KEYS.length};}
function getSheet(){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(SHEET_NAME);if(!sh)throw new Error('Sheet Employees was not found');return sh;}
function ensureSheetShape(sh){if(sh.getLastColumn()<FIELDS.length)throw new Error(`Sheet ${SHEET_NAME} has ${sh.getLastColumn()} columns; ${FIELDS.length} are required.`);}
function isAuthorized(token){const properties=PropertiesService.getScriptProperties();const allowed=String(properties.getProperty(ALLOWED_EMAILS_PROPERTY)||'').split(',').map(email=>email.trim().toLowerCase()).filter(Boolean);if(allowed.length){const email=String(Session.getActiveUser().getEmail()||'').trim().toLowerCase();return Boolean(email)&&allowed.indexOf(email)!==-1;}const required=properties.getProperty(TOKEN_PROPERTY);return !required||String(token||'')===required;}
function doGet(e){try{const parameters=(e&&e.parameter)||{};if(!isAuthorized(parameters.token))return json({ok:false,error:'Unauthorized request.'});const action=parameters.action||'list';if(action==='download')return csvDownload();if(action!=='list')return json({ok:false,error:'Unknown action'});return json({ok:true,employees:readEmployees()});}catch(err){return json({ok:false,error:errorMessage(err)});}}
function doPost(e){let lock;try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(!isAuthorized(body.token))return json({ok:false,error:'Unauthorized request.'});if(body.action!=='update'&&body.action!=='create')return json({ok:false,error:'Unknown action'});lock=LockService.getScriptLock();lock.waitLock(30000);const employee=body.action==='update'?updateEmployee(body.employee||{}):createEmployee(body.employee||{});return json({ok:true,employee:employee});}catch(err){return json({ok:false,error:errorMessage(err)});}finally{if(lock)lock.releaseLock();}}
function errorMessage(err){return err&&err.message?err.message:String(err);}
function readEmployees(){const sh=getSheet();ensureSheetShape(sh);const values=sh.getDataRange().getDisplayValues();return values.slice(1).filter(row=>row.some(Boolean)).map((row,index)=>rowToObject(row,index+2));}
function rowToObject(row,rowNumber){const employee={rowNumber:rowNumber};FIELDS.forEach((field,index)=>employee[field[0]]=row[index]||'');employee.id=employee.code||String(rowNumber);return employee;}
function normalizeCode(value){return String(value||'').trim().toLowerCase();}
function validateEmployee(sh,input,rowNumber){const code=String(input.code||'').trim(),name=String(input.name||'').trim();if(!code||!name)throw new Error('Employee code and name are required.');const lastRow=sh.getLastRow();if(lastRow<2)return;const codes=sh.getRange(2,1,lastRow-1,1).getDisplayValues();const duplicate=codes.some((entry,index)=>normalizeCode(entry[0])===normalizeCode(code)&&(index+2)!==rowNumber);if(duplicate)throw new Error('An employee with this code already exists.');}
function valuesForWrite(input){return FIELDS.map(field=>COMPUTED.has(field[0])?null:(input[field[0]]===undefined?'':input[field[0]]));}
function updateEmployee(input){const sh=getSheet(),row=Number(input.rowNumber);ensureSheetShape(sh);if(!Number.isInteger(row)||row<2||row>sh.getLastRow())throw new Error('The employee row was not found.');validateEmployee(sh,input,row);sh.getRange(row,1,1,FIELDS.length).setValues([valuesForWrite(input)]);writeDerivedFormulas(sh,row);SpreadsheetApp.flush();return rowToObject(sh.getRange(row,1,1,FIELDS.length).getDisplayValues()[0],row);}
function createEmployee(input){const sh=getSheet();ensureSheetShape(sh);validateEmployee(sh,input,0);sh.appendRow(valuesForWrite(input));const row=sh.getLastRow();writeDerivedFormulas(sh,row);SpreadsheetApp.flush();return rowToObject(sh.getRange(row,1,1,FIELDS.length).getDisplayValues()[0],row);}
function writeDerivedFormulas(sh,row){sh.getRange(row,16).setFormula('=IFERROR(DATEDIF(M'+row+',TODAY(),"Y"),"")');sh.getRange(row,17).setFormula('=IF(P'+row+'="","",IF(P'+row+'<30,"أقل من 30",IF(P'+row+'<40,"من 30 إلى 39",IF(P'+row+'<50,"من 40 إلى 49",IF(P'+row+'<60,"من 50 إلى 59","60 فأكثر")))))');sh.getRange(row,18).setFormula('=IFERROR(DATEDIF(M'+row+',O'+row+',"Y"),"")');sh.getRange(row,19).setFormula('=IFERROR(DATEDIF(O'+row+',TODAY(),"Y")&" سنة و "&DATEDIF(O'+row+',TODAY(),"YM")&" شهر","")');}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function csvDownload(){const values=getSheet().getDataRange().getDisplayValues();const csv='\uFEFF'+values.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');return ContentService.createTextOutput(csv).setMimeType(ContentService.MimeType.CSV);}
